language: python
python:
 - "2.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install swig

install:
  - pip install --no-deps -r requirements.txt --use-mirrors
script: nosetests
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
